#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/bootparamd,v 1.1.1.1 2014/04/13 15:16:31 miod Exp $

daemon="/usr/sbin/rpc.bootparamd"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_pre() {
	[ -s /etc/bootparams ]
}

rc_cmd $1
