#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/mopd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/sbin/mopd"
daemon_flags="-a"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_pre() {
	[ -d /tftpboot/mop ]
}

rc_cmd $1
