#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/nfsd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/sbin/nfsd"

. /etc/rc.d/rc.subr

pexp="(${daemon}( |$)|nfsd: (master|server)$)"

rc_reload=NO

rc_pre() {
	[ -s /etc/exports ] && grep -qv '^#' /etc/exports
}

rc_cmd $1
