#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/nginx,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/sbin/nginx"

. /etc/rc.d/rc.subr

pexp="nginx:.*master.*process"

rc_reload() {
	${daemon} -s reload
}

rc_stop() {
	${daemon} -s stop || pkill -f "^${pexp}"
}

rc_cmd $1
