#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/spamd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/libexec/spamd"

. /etc/rc.d/rc.subr

pexp="spamd: \[priv\]"
rc_reload=NO

rc_pre() {
	[ X"${spamd_black}" != X"NO" ] && \
		daemon_flags="-b ${daemon_flags}"
	return 0
}

rc_start() {
	${rcexec} "${daemon} ${daemon_flags} ${_bg}"
	spamd_setup_flags="-D"
	[ X"${spamd_black}" != X"NO" ] && \
		spamd_setup_flags="-b ${spamd_setup_flags}"
	rc_do rc_wait start && /usr/libexec/spamd-setup ${spamd_setup_flags}
}

rc_cmd $1
