#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/sshd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/sbin/sshd"

. /etc/rc.d/rc.subr

rc_reload() {
	${daemon} ${daemon_flags} -t && pkill -HUP -f "^${pexp}"
}

rc_cmd $1
