#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/syslogd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/sbin/syslogd"

. /etc/rc.d/rc.subr

pexp="syslogd: \[priv\]"

rc_pre() {
	[ X"${nginx_flags}" != X"-u" ] && rm -f /var/www/dev/log && \
		daemon_flags="${daemon_flags} -a /var/www/dev/log"
	[ X"${named_flags}" != X"NO" ] && rm -f /var/named/dev/log && \
		daemon_flags="${daemon_flags} -a /var/named/dev/log"
	[ X"${nsd_flags}" != X"NO" ] && rm -f /var/nsd/dev/log && \
		daemon_flags="${daemon_flags} -a /var/nsd/dev/log"
	[ X"${unbound_flags}" != X"NO" ] && rm -f /var/unbound/dev/log && \
		daemon_flags="${daemon_flags} -a /var/unbound/dev/log"
	[ -d /var/empty ] && rm -f /var/empty/dev/log && \
		mkdir -p -m 0555 /var/empty/dev && \
		daemon_flags="${daemon_flags} -a /var/empty/dev/log"
	rm -f /dev/log
}

rc_cmd $1
