#!/bin/sh
#
# $OpenBSD: src/lib/libssl/src/etc/rc.d/yppasswdd,v 1.1.1.1 2014/04/13 15:16:32 miod Exp $

daemon="/usr/sbin/rpc.yppasswdd"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_pre() {
	[ X"`domainname`" != X"" -a -d /var/yp/`domainname` ] || \
		return 1
	_host1=`ypwhich -m passwd 2> /dev/null`
	_host2=`hostname`
	if [ `grep '^lookup' /etc/resolv.conf | grep yp | wc -c` -ne 0 ]; then
		_host1=`ypmatch $_host1 hosts | cut -d' ' -f2`
		_host2=`ypmatch $_host2 hosts | cut -d' ' -f2 | head -1`
	else
		_host1=`echo $_host1 | nslookup | grep '^Name: ' | \
			sed -e 's/^Name:    //'`
		_host2=`echo $_host2 | nslookup | grep '^Name: ' | \
			sed -e 's/^Name:    //'`
	fi
	[ "$_host2" = "$_host1" ]
}

rc_cmd $1
